### ISSUE TITLE
Find issues to resolve for this lesson

### ISSUE THREAD

**Issue by weaverbel** [LibraryCarpentry/lc-git#2] opened 2018-05-09 02:31 UTC
This lesson has now been migrated to the Library Carpentry organisation. All updates and new issues should happen on THIS repo.

All the issues that need resolving are still at the old location, however: https://github.com/data-lessons/library-git-DEPRECATED/issues

Find issues to resolve *there* and fix them **here**.

**Comment by VickySteeves** [comment] 2018-05-10 15:28
This is a duplicate of #1 and should probably be closed to avoid confusion.

**Closed** 2018-05-14 00:54 UTC
Labels: mozsprint
